// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAXFmBieaHRmkMbU84TaswuJBSs427QA',
    appId: '1:647987908824:web:0939bb5406d51ffee847ad',
    messagingSenderId: '647987908824',
    projectId: 'amaricancandy-c87c3',
    authDomain: 'amaricancandy-c87c3.firebaseapp.com',
    storageBucket: 'amaricancandy-c87c3.firebasestorage.app',
    measurementId: 'G-KKMWLXHGCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa6gG6gMhBMGYVV1BdyjRmZhodUrZdw2Y',
    appId: '1:647987908824:android:cd75dfea77e7010ee847ad',
    messagingSenderId: '647987908824',
    projectId: 'amaricancandy-c87c3',
    storageBucket: 'amaricancandy-c87c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEVRGdc5D0FdONbeWdthfH_WoD24tI9SA',
    appId: '1:647987908824:ios:f67bb6d6a3e7babfe847ad',
    messagingSenderId: '647987908824',
    projectId: 'amaricancandy-c87c3',
    storageBucket: 'amaricancandy-c87c3.firebasestorage.app',
    androidClientId: '647987908824-iuulk4gu73tesh4oln0qe8knojik8051.apps.googleusercontent.com',
    iosClientId: '647987908824-jhcuq8tic380dno5fafnddg08kttreo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopHopProkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrxpkvtDO1YMP5VV3doRb5SElWIbqskhY',
    appId: '1:3467566872:ios:83eee9666ff89534bd886d',
    messagingSenderId: '3467566872',
    projectId: 'americancandy-1c25f',
    storageBucket: 'americancandy-1c25f.firebasestorage.app',
    iosBundleId: 'com.example.shopHopProkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-W8H2Q_a_Ngce-YK4DGJIXipRzVlumIk',
    appId: '1:3467566872:web:c8caa8f62639eccfbd886d',
    messagingSenderId: '3467566872',
    projectId: 'americancandy-1c25f',
    authDomain: 'americancandy-1c25f.firebaseapp.com',
    storageBucket: 'americancandy-1c25f.firebasestorage.app',
    measurementId: 'G-0BDGKPYBZ6',
  );
}